zowe/zlux-server-framework

js/index.js, js/package-lock.json, js/package.json, js/plugin-loader.js
Tested as working - used during SHARE. Room for improvement by supporting websockets and swagger output next.
=> Add support for mediation layer through setting up servers root as a eureka endpoint

js/index.js, js/webapp.js
Import resolution failure would not wait for dependencies to resolve, causing import failure. This fixes it
Signed-off-by: Sean Grady <sgrady@rocketsoftware.com>
=> Import resolution failure bugfix

js/proxy.js, js/webapp.js
Proxy Server will now:
- try to redirect 404's using the "Referer" header.
- proxy better
=> Added additional redirection logic

js/package-lock.json, js/package.json, js/plugin-loader.js, js/translation-utils.js, js/webapp.js
Test with: 
* https://github.com/zowe/sample-angular-app/pull/7
* https://github.com/zowe/zos-subsystems/pull/5
=> Internationalization of plugin definitions

js/plugin-loader.js
- add a field for pluginDefinition.json, "copyright" for displaying purpose.
=> add copyright field in pluginDefiniton loader.

js/webapp.js
=> Updating server so that it doesnt assume http port is always available

js/webapp.js
Signed-off-by: Baoyuan Xing <bxing@rocketsoftware.com>
=> proxied host info for plugin usage

js/depgraph.js, js/plugin-loader.js
=> Printing out a warning when a duplicate plugin identifier is found.

js/plugin-loader.js, js/webapp.js
=> Location of plugin on file system should not longer be supplied

js/index.js
=> Making zss check optional

Jenkinsfile
Jenkinsfile contains a multi-branch pipeline.
- the pipeline builds zlux superproject and run "npm test"
- if PR is related to other PRs, the pipeline can be re-started manually and PR numbers can be specified
Signed-off-by: Dmitry Nikolaev <dnikolaev@rocketsoftware.com>
=> Run unit tests via Jenkinsfile

lib/apiml.js, lib/index.js, lib/webserver.js
Replaces https://github.com/zowe/zlux-server-framework/pull/59
=> Use the zlux server TLS certificates and key for client authentication to the APIML

lib/jsonUtils.js, lib/util.js, plugins/config/lib/configService.js, test/webapp/webapp.js, test/webserver/multibind.js
=> Switching _unp loggers to _zsf (zlux server framework)

lib/webapp.js
Switches server to mode that conditionally sets secure flag on cookie… based on whether client connects from HTTP or HTTPS
=> Use secure attribute for session cookie

.gitignore, lib/apiml.js, lib/index.js
Signed-off-by: Reet Chowdhary <rchowdhary@rocketsoftware.com>
=> changes to apiml registration

.gitignore, lib/apiml.js, lib/auth-manager.js, lib/index.js, lib/webapp.js, lib/webauth.js, package-lock.json, plugins/terminal-proxy/lib/terminalProxy.js, plugins/trivial-auth/lib/trivialAuth.js, test/webapp/config.js
Update master to v1.1.0
Signed-off-by: Dmitry Nikolaev dnikolaev@rocketsoftware.com
=> Update master to v1.1.0

plugins/config/lib/configService.js, plugins/terminal-proxy/lib/terminalProxy.js
Potential fixes for https://github.com/zowe/zlux-server-framework/issues/88 based off inspection that turned up some loose ends in 2 plugins
=> Fixes for config & terminal proxy

plugins/config/lib/configService.js
=> Added html obfuscation to config service.

plugins/config/lib/configService.js
It needs to go up one additional directory. An error was made during last PR. @dmitrynikolaev
=> Fixed bad module path.

plugins/config/lib/configService.js, plugins/config/pluginDefinition.json
Signed-off-by: Sean Grady <sgrady@rocketsoftware.com>
=> Version bump for config service

plugins/config/doc/swagger/data.yaml, test/webapp/config.js
Signed-off-by: Reet Chowdhary <rchowdhary@rocketsoftware.com>
=> added license

lib/webapp.js
https://github.com/zowe/zlux-server-framework/issues/89
=> Add urlPrefix override to service type "service"

lib/plugin-loader.js, package.json
Signed-off-by: aarora4 <lazyc78@gmail.com>
appending to node path
=> script for changing NODE_PATH

test/webapp/webapp.js
=> Unit test was missing essential config info

lib/clusterManager.js, lib/util.js, lib/webapp.js
Utilizing changes in https://github.com/zowe/zlux-shared/pull/17
=> Adding new logging abilities

utils/install-app.js
=> Changing default permissions for installing of plugin

lib/util.js, lib/webapp.js
Added ID <---> message log maps to dataservices
Log messages housed in /lib/assets/i18n/log/messages_**language**.json
=> Added message logging to the generated loggers for dataservices

plugins/config/lib/configService.js
=> Consolidate routers for cleanup, and add HEAD to GET

lib/webapp.js
Created promise to return environment details, improving performance when making concurrent requests
=>  /server/environment performance improvement

lib/webapp.js
=> Proxies url got clobbered by rbac check

lib/webapp.js
=> Warn for missing attribute for library plugin. Add gzip, brotli support

package.json, utils/install-app.js
=> Make userinput and pluginsdir accessible from other functions

lib/webapp.js, lib/webauth.js
/server/proxies has no reason to need auth, move it out to simplify RBAC
And, cleanup of the logout procedure
=> Few auth fixes

lib/index.js, lib/proxy.js, lib/webapp.js, lib/webauth.js, package-lock.json
- Pass through express router ws patcher in case it is needed by plugins (on my system, for some reason router.ws was missing on one plugin)
- Allow security plugins to manage headers that are proxied, so that things not needed by the browser are not put in
- Clear cookie on complete logout
=> Cookie & WS changes

lib/webapp.js, lib/webauth.js, package.json, plugins/config/lib/configService.js, test/webapp/config.js
Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>
=> Added support for allowed plugins for certain users when rbac is enabled

lib/apiml.js, lib/index.js
https://github.com/zowe/zlux/issues/252
Add ability to read eureka overrides
=> ability to add eureka overrides

plugins/config/lib/configService.js
=> Do not merge override object if null due to bad parse

lib/index.js, lib/plugin-loader.js
Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>
=> Server Up message added

lib/clusterManager.js
Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>
=> Changed env variable names to something more zlux specific

lib/auth-manager.js, lib/clusterManager.js, lib/process.js, lib/unp-constants.js, lib/webapp.js, lib/webauth.js, lib/webserver.js
Fixed looping caused by cluster not knowing when to keep workers stopped when unrecoverable issue spotted.
Also, did some variable name cleanup, since references to UNP are quite old.
=> Invalid configuration looping fix

lib/webauth.js
=> Array check before using array map function

utils/install-app.js
=> Adding message loading for install app

lib/util.js, lib/webapp.js
Resolves https://github.com/zowe/zlux/issues/400
=> Fix for when logLanguage is not specified in config

lib/webauth.js
=> Have auth login and refresh tell client what the default category is

lib/util.js
Before: 
`2020-03-30 16:55:03.101 <ZWED:34013428> TSSPG INFO (_zsf.install,index.js:261) ZWED0290I org.zowe.configjs 91 21 23 96 22 23`
After: 
`2020-03-30 17:01:17.018 <ZWED:17236202> TSSPG INFO (_zsf.install,index.js:261) ZWED0290I - Plugin (org.zowe.terminal.proxy) loaded. Successful: 57% (13/23) Attempted: 61% (14/23)`
=> Fixes unformatted messages when language not specified

lib/clusterManager.js
Add missing pluginId argument.
=> Fix setStorageAll method

lib/webapp.js, plugins/config/lib/assets/i18n/log/messages_en.json
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
=> Fixed a non-unique error id

lib/jsonUtils.js
=> Fixed undefined reference

lib/webauth.js
=> Fix so that cookies are not returned via body, only header

CHANGELOG.md, lib/index.js, lib/proxy.js
Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>
=> Added node server to retry if initial connection to the server fails

plugins/sso-auth/lib/ssoAuth.js
=> Tie sso use to if zss can handle it

lib/proxy.js, lib/webserver.js
=> Wrong conditional caused breakage on linux, windows

lib/webapp.js
Fix for `DataserviceStorage.deleteAll()` method.
=> Fix DataserviceStorage.deleteAll method

plugins/terminal-proxy/lib/terminalProxy.js
Was set in development, but missing from prior commits.
=> Missing line to set logger

CHANGELOG.md, utils/argumentParser.js
Check the test case at the bottom of the file which prints out:
```
ZWED0139I - Input = {
"node_mediationLayer_server_gatewayPort": "$GATEWAY_PORT",
"node_mediationLayer_server_port": "$DISCOVERY_PORT",
"node_mediationLayer_enabled": "true",
"node_https_certificates": "${KEYSTORE}&${KEY_ALIAS},",
"node_https_certificateAuthorities": "${KEYSTORE_CERTIFICATE_AUTHORITY},${EXTERNAL_ROOT_CA}",
"agent_jwt_fallback": "$SSO_FALLBACK_TO_NATIVE_AUTH",
"productDir": "$ROOT_DIR/components/app-server/share/zlux-app-server/defaults",
"node_https_port": "$ZOWE_ZLUX_SERVER_HTTPS_PORT",
"node_https__x2dnegative": "-1",
"logLevels__x5fzsf____auth": "1",
"logLevels_org____zowe____terminal____tn3270_x2e_x2a": "5"
}
ZWED0140I - Output = {
"node": {
"mediationLayer": {
"server": {
"gatewayPort": …
```
=> Solution to config objects that were edge cases to env vars

lib/webauth.js
Include Auth Capabilities into Auth Result if possible.
This PR is pre-req for https://github.com/zowe/zlux-app-manager/pull/253
=> Include Auth Capabilities into Auth Result

plugins/terminal-proxy/lib/ssh.js
Adding window size patch for ssh when large messages are sent
=> SSH bugfix for window size

CHANGELOG.md, plugins/sso-auth/lib/zssHandler.js
=> Use instance ID from config

README.md, lib/webapp.js, test/docker/appServerHandshake.js
Simple test of plugins GET call for app server
=> Simple test of plugins GET call for app server

CHANGELOG.md, lib/assets/i18n/log/messages_en.json, lib/util.js, lib/webserver.js, package-lock.json, package.json
This pull request implements the following feature:
- Add support for certificates and certificate authorities stored within PKCS12 files.
=> PKCS12 support

lib/assets/i18n/log/messages_en.json, lib/index.js, lib/plugin-loader.js, lib/webapp.js
How to use? 
Change plugin definition to conform to new proposal in: https://github.com/zowe/zlux/wiki/ZLUX-Plugin-Definition-&-Structure#general-attributes
For example (in the Editor)
```
{
"identifier": "org.zowe.editor",
"apiVersion": "1.0.0",
"pluginVersion": "2.2.1",
"license": "EPL-2.0",
"author": "Zowe",
"homepage": "https://github.com/zowe/zlux-editor",
"pluginType": "application",
"webContent": {
"framework": "angular",
"launchDefinition": {
"pluginShortNameKey": "editorTitle",
"pluginShortNameDefault": "Editor",
"imageSrc": "assets/icon.png"
},
"descriptionKey": "MyPluginDescription",
"descriptionDefault": "Zowe Editor",
"defaultWindowStyle": {
"width": 1200,
"height": 600
}
},
"configurationData": {
"resources": {
"ui": {
"aggregationPolicy": "override",
"subResources": { …
```
=> Plugin JSON attributes & requirements checking

lib/plugin-loader.js
A slightly cleaned up version of https://github.com/zowe/zlux-server-framework/pull/245 which uses a promise that is yielded rather than a coroutine.
=> Node6 fix: Switch from async to promise and coroutine

lib/plugin-loader.js
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
=> Adjusted small edgecase

lib/assets/i18n/log/messages_en.json
Update to include log message in https://github.com/zowe/zlux-app-server/pull/139
=> Updating logs

plugins/sso-auth/lib/safprofile.js, plugins/sso-auth/lib/zssHandler.js
This PR repeats https://github.com/zowe/zss-auth/pull/27 made by @NakulManchanda for zss-auth.
=> Fix for sso-auth for URLs with special chars

lib/assets/i18n/log/messages_en.json, lib/default-remote-app-template.html, lib/util.js, lib/webapp.js
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>
Add support for new destination property to iframe pluginDefinition.json
Add new double iframe default template
=> add pluginId/iframe route

lib/util.js
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>
=> refactor makeRemoteUrl, add ZOWE_EXPLORER_HOST option

CHANGELOG.md, lib/apiml.js
=> Change default retry attempts

lib/index.js, lib/plugin-loader.js, lib/proxy.js, lib/webapp.js, plugins/sso-auth/lib/ssoAuth.js
Related PRs:
- TLS Support zowe/zss#226
- Cipher suite definitions zowe/zowe-common-c#199
- Automate TLS setup for zss zowe/zlux-app-server#151
Linked issue: zowe/zlux#632
=> TLS support for ZSS agent

lib/webapp.js
Signed-off-by: Leonty Chudinov <lchudinov@rocketsoftware.com>
=> Hotfix: Fix TLS options for agent

lib/webapp.js
This PR initializes cookie secret based on server's private key.
=> Initialize App server cookie secret based on shared environment objects

lib/apiml.js
This is the same as https://github.com/zowe/zlux-server-framework/pull/286 but for the staging branch
=> APIML cert bugfixes - staging

lib/apiml.js
Same as https://github.com/zowe/zlux-server-framework/pull/288
=> Increase default timeout to 5 minutes

CHANGELOG.md, lib/swagger-catalog.js
This PR addresses Issue: https://github.com/zowe/zlux/issues/422
This PR changes 2 warnings messages to debug, as they were warnings to developers, not to users.
This just changes log message verbosity.
=> Switch swagger warnings to debug

CHANGELOG.md, lib/plugin-loader.js
This PR is https://github.com/zowe/zlux-server-framework/pull/303 but for the staging branch.
=> Fix parameter mismatch

CHANGELOG.md, lib/webapp.js, lib/webserver.js, plugins/terminal-proxy/lib/terminalProxy.js
This PR addresses Issue: https://github.com/zowe/zlux/issues/512
144w was never a real issue, just a logging error, but the proper way to fix it seems to be to give plugins the list of tls options that the server loads up, since the plugin was trying to load tls options itself and failing and i didn't want to fix it by duplicating logic. however, plugins should not get the same tls object that the server uses itself, so one is cloned.
When using keyrings, error 144w would print. With this change, it will not print because the terminal proxy does not try to load key content on its own anymore. the 144w message has been removed from use.
=> Fixed keyring warning from terminal proxy

lib/util.js, lib/webapp.js, lib/webauth.js, plugins/sso-auth/lib/apimlHandler.js, plugins/sso-auth/lib/ssoAuth.js
This PR makes cookie from one app-server readable by another.
This PR addresses Issue: TBD
* SSO has to be enabled
* org.zowe.zlux.auth.trivial.json plugin has to be removed from the list of app-server plugins
=> HA: Make cookie from one app-server readable by another

CHANGELOG.md, lib/proxy.js
This adds support to the proxy utility for the PATCH method, and it is treated the same as the POST and PUT methods.
If you have a webserver that supports PATCH, and you want to issue PATCH as a client to the app-server, intending it to be proxied to the destination, then previously the app-server would not do it but with this PR it will. This is being tested by an extender so we'll see if it works for them, but that's the general concept to test.
This PR was made upon request by extenders who were having problems specifically with PATCH not being supported in the proxy, and with this fix it is confirmed to work for them, so it should be no …
=> Add proxy patch support

lib/webapp.js, lib/webauth.js, plugins/config/lib/configService.js
This PR addresses issues that I discovered using [lgtm](https://lgtm.com/) code scanner.
=> Fix issues discovered by LGTM

CHANGELOG.md, lib/unp-constants.js, lib/webserver.js
This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]
You can test that the ciphers work in the way expected (tls 1.2 min, tls 1.3 max, tls 1.3 ciphers do not work in tls 1.2) by disabling the ciphers one by one to see what the browser will load, and check browser info to see what tls was used. In firefox you can also use about:config to alter what tls the browser itself supports, to prove that lower tls is not used.
=> Add ciphers to enable use of tls 1.3

CHANGELOG.md, lib/index.js
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
App server doesn't start when no agent information is present. This is wrong because in trivial-auth, we don't need any agent information. 
=> Fix small JS error to make trivial-auth work

lib/webapp.js
This PR adds CAs to agent request options.
=> Add CAs to agent request options

plugins/sso-auth/lib/ssoAuth.js, plugins/sso-auth/lib/zssHandler.js
This PR addresses Issue: https://jira.rocketsoftware.com/browse/MVD-4234
- APIML does not know the password expired, so it responds with 401, while ZSS does know that the password expired.
- Because in this configuration zlux is talking to both zss and apiml, there was a confusion about which response to send back: apiml 401 or zss message.
- The fix is made for this specific case by sending back the zss message instead of the apiml one
- This allows the user to rest the expired password.
=> Resetting an expired password if authentication is done using both apiml and zss

lib/assets/i18n/log/messages_en.json, lib/webserver.js
This PR addresses Issue: https://jira.rocketsoftware.com/browse/MVD-4707
- Zowe environment variables only state what root CA is and App server doesn't know there are other CA's 
- So if App server receives a certificate which is signed by an intermediate, that the App server doesn't know about, it will reject it as an unknown certificate.
- Therefore in this PR we try to load every CA we find in the keyring.
=> Certificate Chain Loading

lib/apiml.js, plugins/trivial-auth/lib/trivialAuth.js
This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]
=> Bugfix: Enable trivial auth via APIML token

plugins/sso-auth/lib/ssoAuth.js
This PR removes dependency on PKCS11 token. 
This PR addresses Issue: https://github.com/zowe/zss/issues/365
This PR depends upon the following PRs: https://github.com/zowe/zss/pull/363
=> Remove dependency on PKCS11 token

utils/argumentParser.js
Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
Variables read by Desktop or ZSS are updated with valid prefixes
ZWED_ - Desktop and/or ZSS,
ZWES_ - ZSS but not the Desktop or ZIS
ZOWE_ZLUX_SERVER_HTTPS_PORT --- ZWED_SERVER_HTTPS_PORT
zowe/zowe-install-packaging#2478
=> [v2]updated env var names with consistent prefixes

lib/apiml.js, lib/util.js, plugins/sso-auth/lib/apimlHandler.js
Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]
=> updated apiml path pattern

plugins/sso-auth/lib/zssHandler.js
This is a small change to expect the same cookie name that zss generates from https://github.com/zowe/zss/pull/384/files
=> Adjust to look for new zss cookie name

lib/webapp.js
PR attempts to make requests to ZSS happen w/o any loopbacks to the App server.
=> Direct Routing

lib/webauth.js, plugins/sso-auth/lib/apimlHandler.js, plugins/sso-auth/lib/ssoAuth.js, plugins/sso-auth/lib/zssHandler.js
To better understand cases such as https://github.com/zowe/zlux/issues/761
This PR is just to add some more messages so we can learn if there are unexpected calls to servers that would result in multiple auth events rather than 1.
=> Tracing auth handler server activity

utils/yamlConfig.js
This PR allows `haInstanceId` to be `undefined` because it's possible in development environment.
=> Allow haInstanceId to be undefined

CHANGELOG.md, package-lock.json, package.json
Resolves https://github.com/zowe/zlux/issues/766 just a package and package-lock update to newest keyring_js version
=> Fix issue 766 by updating package, package-lock

CHANGELOG.md
This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]
=> Fix release note
