zowe/zlux-server-framework

- js/index.js
- js/process.js
Nodes in cluster get restarts so this exception area should be rare
> Let server die on uncaught exception instead of accumulating leaks.

- js/plugin-loader.js
- js/webserver.js
Incorporate the changes made by Nathan Drewniak. Slightly modify what
he's done:
- print the path to the HTTPS certificates
- more detailed info about plugin loading: print the full path to the
reference and to the plugin folder, print the plugin type
Based on: https://github.com/gizafoundation/zlux-proxy-server/pull/30
Signed-off-by: Fyodor Kovin <fkovin@rocketsoftware.com>
> MVD-709 Node server tracing

- js/webapp.js
Imports were failing when the name of both were not identical due to wrong variable being used
> Imports were failing when the name of both were not identical

- js/package-lock.json
- js/package.json
- js/webserver.js
All browsers that zlux supported already supported tls 1.2.
You can test behavior in firefox by changing about:config's security.tls.version.max to lower than 3.
> Removed support for tls 1.1 and tls 1.0. 

- js/index.js
- js/plugin-loader.js
- js/webapp.js
It appears that the ng2 module logic was an attempt at some early ideas on how to build a web desktop, that were not needed as a result of adoption of webpack, resulting in some dead code that printed warnings a lot.
> Removing dead code that resulted in pointless warnings

- js/webapp.js
logic for when resource doesnt exist was able to enter a case in which the server would do nothing: neither try to interpret it as a proxied request that escaped the proxy, nor a reference to a missing object.
Solution is just to add do404 to the right place.
> Missing call to 404 handler if ref header is missing

- js/index.js
- js/proxy.js
Node code running on Windows should check if auth services host is configured, and issue clear instructions if not configured.
> Check availability of proxied server

- js/webapp.js
Somehow conflict resolution resulted in this.plugins.push appearing twice in install plugin
> Fix /plugins showing each plugin twice

- js/package-lock.json
toposort was removed and semver was added in package.json, but package-lock.json did not have these changes.
> Updating package-lock to be able to do npm ci

- js/util.js
dns lookup should throw for invalid hostnames, but for some reason does not throw when given the boolean 'false', so do a string check first.
Signed-off-by: Sean Grady <sgrady@rocketsoftware.com>
> Bugfix for disallowing non-strings such as false to be put in as potential IPs for binding

- js/webapp.js
- plugins/config/pluginDefinition.json
- plugins/terminal-proxy/pluginDefinition.json
Resolves https://github.com/zowe/zlux-proxy-server/issues/36
This adds headers to all dataservice calls (unless opt-out at service level or individual call level) which instructs browsers not to cache a response. This is useful for sensitive information or calls that have no need to be cached.
> Added conditionally used middleware to add no-caching headers for secure APIs

- js/plugin-loader.js
- test/plugin-loader/depgraph.js
- test/webserver/multibind.js
zlux-proxy-server was renamed to zlux-server-framework, and zlux-example-server was renamed to zlux-app-server. There was some hardcoding so this should remedy it.
> Updating old proxy and example paths to app server and framework

- plugins/config/lib/configService.js
Body check for PUT was insufficient: body parser logic would set the body to an object if empty, so the existence check for a string was failing.
Now, check for a string, and check that it's JSON (also catches empty case)
> Reject put if body is missing or not JSON

- lib/webapp.js
Related to https://github.com/zowe/zss/issues/11, just filling in headers for some services that were missed during the last round of header fixes.
This just instructs the browser not to cache these responses, and the effected services don't really gain anything by being cached, so it should be a change without adverse effects.
> Adding no cache headers to root services that had been missed

- lib/webapp.js
Test case that this addresses:
GET /plugins/<script>alert(1)</script>
You don't want to see:
<h1>Resource not found, URL: <script>alert(1)</script></h1></br><h2>Additional info: ZLUX: unknown resource requested</h2>
Just in case the browser tries to load a malicious script through this.
Chrome and Postman both do not actually trigger this, because they URI encode <
However, curl doesn't. So, this is a fix for curl or things that don't URI encode.
> Encode URI to prevent HTML insertion into 404 handler

- lib/webapp.js
Parameter count mismatch resulted in a missing boolean that controlled setting cookie for proxied zss calls, so rest apis that were zss code would fail. In particular, tn3270 discovery api.
> Bugfix for ZSS Dataservice authentication

- plugins/trivial-auth/lib/trivialAuth.js
Config service needs username to get user config
Latest auth code uses auth refresh to do the initial login check
It unconditionally succeeded on trivial auth, even when username wasnt present, so although you were able to login, the config service could not function.
It makes more sense to gate by if a username has been given or not. This is how it was before this bug was introduced.
> Fix config service for trivial auth

- lib/plugin-loader.js
loadTranslations is used to set up a map of translations for UI strings about application names. It was added in #15 but was removed accidentally within #14. This restores it in what seems to be the correct, modern location.
> Restore removed call to load translations of plugin names

- lib/webapp.js
- package-lock.json
- package.json
gzip compression is supported by pretty much everything, and brotli is supported by all browsers Zowe Desktop already supports: https://caniuse.com/#search=brotli
This change makes the server serve static files with a preference for brotli, when present and the browser states it is supported via the accepts headers.
> Add gzip and brotli support for static files

- lib/proxy.js
- lib/webapp.js
Fixes for proxy hitting 404 when it shouldnt, and for when location header is not what was expected
Proxy redirect logic due to sniffing referrer trick did not loop correctly, going right to 404.
And location header logic only worked in a very specific case.
> Proxy fixes

- lib/webapp.js
Signed-off-by: Todd Wellman <twellman@rocketsoftware.com>
> add port to cookie name to differentiate multiple servers on same domain

- lib/plugin-loader.js
Signed-off-by: toddwellman <twellman@rocketsoftware.com>
> make extra unused auth plugins not throw errors

- lib/auth-manager.js
- lib/index.js
- lib/sessionStore.js
- lib/webapp.js
- lib/webauth.js
The zlux cookie used to have a timeout on it, but it didn't make too much sense versus the individual auth timeouts.
Now, this has been removed in favor of server-side tracking, and the server counts an expiration based on the latest timeout for all auths related to a session.
This makes use of the session object that comes from the cluster, so this works both in single process mode and in cluster mode.
> Remove cookie exp & add server exp

- lib/webapp.js
Farther out: need a design for this... can auth handlers have similar attributes to service? If so, then it could be appData.service or appData.auth.
See https://github.com/zowe/zlux-server-framework/pull/106 for a PR that can be used to test behavior.
> Temp workaround for callservice of auth handlers throwing exception

- plugins/terminal-proxy/lib/terminalProxy.js
All terminal messages should be JSON, but in case they arent, close the connection instead of fail
> Exception fix for non-JSON terminal message

- lib/swagger-catalog.js
Fixes that https://github.com/zowe/zlux-server-framework/pull/99 required node8+ due to the keyword "async". Making use of bluebird to support 6 instead.
> Fix for node 6

- lib/index.js
Do not require or create an instance of java manger without a try-catch and only when config requests it
> Try-catch around java manager loading

- lib/webauth.js
- plugins/internal-auth/lib/internalAuth.js
- plugins/trivial-auth/lib/trivialAuth.js
Old authentication handlers which do not support session refreshing will not longer return a 400 or 500 error due to lack of capability, but will allow the session to expire naturally (user logs out/timeout).
Must be merged with:
https://github.com/zowe/zss-auth/pull/19
https://github.com/zowe/zosmf-auth/pull/14
Signed-off-by: Timothy Gerstel tgerstel@rocketsoftware.com
> Compatibility for auth handlers without refresh (Revisited)

- lib/util.js
Use English as a fallback for log messages, so for example:
English
**"Z0001", "Z0002", "Z0003"**
Russian
**"RU001"**
A Russian-selected server log message now has
**"Z0001", "Z0002", "Z0003"** & **"RU001"** instead of just **"RU001"**
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
> Use English as a fallback for log messages

- lib/plugin-loader.js
- plugins/config/lib/configService.js
To solve the issue of how plugins can ship default behavior that can be overridden while having read-only directories for server & plugins, plugins must keep their default config files within their root folder. So, the config service must be made to locate the plugin directory to read there as part of its decision making as to what config gets returned. This turns **plugin** into the new broadest scope of config service, but otherwise has the characteristics of the **product** scope.
> Retreive plugin default config from plugin dir

- plugins/config/lib/configService.js
Enhances the config service to support working with files other than JSON.
Non-JSON are treated as opaque files, where attribute merging will not be performed.
But, you can for example get & put JPEGs.
This requires a "resource" to be marked as binary, rather than JSON, so that there is no mix-and-match.
Some config service modes work on multiple JSON which could be aggregated into a single response. This doesn't make sense for binary, so some of these modes are not supported.
Binary files could be much larger than JSON. And expressjs limits the body size of a PUT/POST message to 100kb by default. So, for binary, this is put at 3mb at first, and we can change this number later on as the need arises.
This changes the parsing of the body slightly in that Content-Type text/plain will now be …
> Support binary mode for config

- lib/webapp.js
This pull request fixes the following:
Ability to set log levels by pattern which causes errors relating to SAF profile names.
Change error messages to JSON response
Only plugins of type "application" can be removed
> Remove POST /server/logLevels/pattern/.  Users now only able to remove applications

- plugins/config/lib/configService.js
In order to not cause regression, still support text/plain json and binary text/plain at the same time by attempting to parse the buffer into utf8. If it fails, give up.
> Add back support for text-plain json

- lib/webapp.js
This pull requests fixes the following:
HTTP methods other than the intended call would return 404 rather than an error message.  Routes now return 405 for invalid methods.
> Added error message for invalid http methods (server status REST API)

- lib/webapp.js
Sometimes, the server would be in the process of reloading when the response was being sent.  This instance would result in some of the response body being dropped, such as end brackets.
> Added fix for PUT /plugins and DELETE /plugins/:id returning invalid JSON

- plugins/config/lib/configService.js
Did not seem to be a big reason to use uint8array, and added a bounds check on neverending write
> Tweak how binary is written to work around behavior of node6 on zos

- lib/webapp.js
- package-lock.json
I found a strange case. I had a dataservice that wanted to use router.ws from express-ws applying .ws to an express router, but router.ws was not found even though it should have existed.
I'm unsure why, but I was able to fix it by utilizing the more explicit method of getting router.ws: utilize a function in express-ws to patch a router.
> Provide express-ws router function to dataservices

- utils/argumentParser.js
This allows for you to specify env vars that can be interpreted as some composite JSON-like structure.
Limitations in the code commends: This is biased towards relatively human-readable JSON attribute names, so the regex used is not flawless but simplistic and will fail fast on purpose if given bizarre input.
How to test: `const parser = require('./argumentParser'); parser.envUnitTest()` and read the output.
> Make an env-to-json function

- plugins/terminal-proxy/lib/ssh.js
- plugins/terminal-proxy/lib/terminalProxy.js
Remove bad practices that make nodejs warn about deprecated buffer usage in node10+
Substituted with equivalent non-deprecated functions.
Before, node will print `(node:5468) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.` but now it will not.
> Remove use of "new Buffer" (deprecated)

- lib/webauth.js
Add ability to get most recent timeout info for auth plugins that cant do a refresh. This way, browser can keep up to date upon page load.
> Get status for auth plugins that cant refresh

- plugins/sso-auth/lib/apimlHandler.js
- plugins/sso-auth/lib/safprofile.js
- plugins/sso-auth/lib/ssoAuth.js
- plugins/sso-auth/lib/tokenInjector.js
- plugins/sso-auth/lib/zssHandler.js
- plugins/sso-auth/pluginDefinition.json
Making a single plugin, called "sso-auth", which is of type "saf".
This is a plugin which will be for SSO in the long run, but it also is able to do just apiml or just zss if one is missing. If both are present, it will use apiml token to give to zss for SSO.
This should not be used as the default auth yet until the standard configuration of Zowe is set to have zss use the SSO token. But, at some point we should switch over to this plugin and stop including zss-auth and apiml-auth.
The code is nearly copy-pasted, in which I put apiml-auth into "apimlHandler.js", and zss-auth into "zssHandler.js", and conditionally call their functions in "ssoAuth.js"
Potential problem: this plugin is of security category "saf", not "zss" or "apiml", so if plugins explicitly requested types "zss" or …
> Combine apiml-auth and zss-auth into one

- lib/index.js
- lib/plugin-loader.js
The messages for plugin loading status did not account for plugins that existed but could not be loaded due to a failure early on.
This fixes one such problem: if a plugin failed to get dataservices set up, it would not be in the array of counted plugins. Now it will be, but will contain an error object, so it can be counted as an error and excluded from further processing.
As an example, before I was reading 15/15 plugins successfully loaded, now I read 15/17 plugins successfully loaded, because one had a require() exception and another was pointing to a folder that didnt exist.
New messages read as:
```
2020-01-30 23:22:44.559 <ZWED:29881> sgrady INFO (_zsf.install,index.js:246) Plugin (org.zowe.terminal.tn3270) loaded.  Successful: 81% (13/16) Attempted: 81% (13/16)
2020-01-30 …
```
> Get correct count of successfully loaded plugins

- lib/clusterManager.js
- lib/webapp.js
Adding an ability for a service to be declared as only for use by other services internally.
This allows for a service to be callable by other services of that plugin via the "callService" function, but does not allow these services to be called from outside of the server. Attempting to call them from outside of the server will be met with a 403 return and an error message.
Since a service is a router and routers are attached internally & externally the same way, the way the server discriminates what is internal vs external in this case is that it checks for the request IP, as well as a code, intended to be only known to the server. If the IP is determined to come from the same host as the server, and the code is valid, then the request is passed on to the router, otherwise the 403 …
> Adding Internal-only services feature

- lib/webauth.js
- plugins/sso-auth/lib/apimlHandler.js
- plugins/sso-auth/lib/ssoAuth.js
- plugins/sso-auth/lib/zssHandler.js
The auth-logout endpoint never reached the security plugins, in case there was something else they should be doing on the backend during the logout process.
Now, if the plugins support it, they are called. This is similar to the logic used for login, except that regardless of what the plugins do, the server core still deletes the session storage area at the end.
> Add plugin logout ability

- lib/assets/i18n/log/messages_en.json
- lib/clusterManager.js
- lib/depgraph.js
- lib/index.js
- lib/jsonUtils.js
- lib/plugin-loader.js
- lib/webapp.js
If node.pluginScanIntervalSec is defined as greater than or equal to 1, then the server will read the plugin folder at that interval to find new plugins to load.
Loading new plugins is the same process as is done at startup, so there is no additional security concern in the process. The only difference is that the plugin loading is async, as opposed to sync that happens during startup.
Due to this command being relatively safe, users can also request this by calling GET /plugins with ?refresh=true. But they must be logged in first.
Because this reads the filesystem, we do not want too many users at once to overwhelm, so it is limited to once per second.
In the case a worker crashes, the bootstrap process picks up the plugins as usual, including these new plugins, so this does not disrupt …
> Search for new plugins on request and or periodically

- lib/webapp.js
Another layer of customization on top of previous PR https://github.com/zowe/zlux-server-framework/pull/173
In this case, server.json (or env, cli) can be used to specify a node.headers section which has objects identical to what is in PR 173. The difference is the attribute "override" which when defined will override whatever the plugin says.
This gives the administrator the ability to set more (or less) restrictive headers to meet their needs.
> Add ability for global headers to exist and possibly override plugins

- lib/clusterManager.js
Setting min workers appeared to never work, max did but printed warnings when you didn't do anything wrong.
> Fixed chatty and incorrect printing of cluster worker count calculations

- lib/apiml.js
- lib/auth-manager.js
- lib/index.js
- lib/plugin-loader.js
- lib/webauth.js
- lib/webserver.js
- plugins/sso-auth/lib/apimlHandler.js
- plugins/sso-auth/lib/ssoAuth.js
- plugins/sso-auth/lib/zssHandler.js
- plugins/sso-auth/pluginDefinition.json
**Release notes:**
**1. API mediation layer token is now held in the browser upon login via the Desktop. This also allows for the Desktop to do single-sign-on login with the token if it is already present in the browser.**
**2. Auth plugins no longer need to be specified explicitly within the server configuration file, the capability remains for backwards compatibility. The server will now auto-detect the auth plugins that are available**
**3. Auth plugins can now be of more than one type, to satisfy environments that have plugins that need access to APIs of similar but different types**
Removed requirement for redundant specification of auth plugins. Added ability for an auth plugin to be of more than one type, and specify it dynamically. Added ability for apiml token to be held in …
> Browser-based apiml token, auth simplification

- lib/clusterManager.js
- plugins/config/lib/assets/i18n/log/messages_en.json
Release note: (probably not needed) Revise error message for cluster storage timeout, and change the default value to better accommodate resource constrained systems.
> Distinguish errors and set cluster timeout to 30s for storage

- CHANGELOG.md
- lib/assets/i18n/log/messages_en.json
- lib/unp-constants.js
- lib/webserver.js
- package-lock.json
- package.json
Release note: Key & certificate data for HTTPS can now be used from SAF keyrings as opposed to only unix files
How does it work?
We use the keyring_js library provided by @vit-tomica and have a special string format to tell when to use it for loading content as opposed to reading a file.
In our config JSON, we have:
```
node: {
https: {
keys: ['path1','path2'],
certificates: ['path3', 'path4']
}
}
```
The path strings used to always be unix file locations. However, now if the strings begin with "safkeyring://" and are in the format of "safkeyring://{user}/{keyringname}&{elementlabel}" then it will be interpreted as a path to find the content in a saf keyring. If the path begins with "file://" it will be treated as a file, and for backwards compatibility if there is no "://", then it will …
> saf keyring support

- CHANGELOG.md
- lib/plugin-loader.js
Plugin api would not respond in the case that a plugin could not load due to a dependency not being met, because that plugin would not get into an array used to check when the processing has finished, so a response would never be generated.
> Fix for plugin rest api request hang

- CHANGELOG.md
- lib/assets/i18n/log/messages_en.json
- lib/plugin-loader.js
Currently, to load a plugin you need a JSON file like this:
```
{"identifier":"org.zowe.configjs",
"pluginLocation":"/zlux-server-framework/plugins/config"}
```
pluginLocation is either an absolute path, or one relative to where the server ran. 
But, it could be more flexible as regards to where something can be relative to.
I added a new attribute, relativeTo, which can be an environment variable if it begins with $, or otherwise a path.
Examples and how they showed up in the logs
```
{"identifier":"org.zowe.configjs",
"pluginLocation":"zlux-server-framework/plugins/config",
"relativeTo": "/me/zlux"}
```
```
2020-05-12 20:59:23.902 <ZWED:16425> me INFO (_zsf.utils,util.js:288) ZWED0051I - Resolved path: zlux-server-framework/plugins/config -> /me/zlux/zlux-server-framework/plugins/config …
```
> Load plugins from different relative paths

- lib/apiml.js
This is a fix for "eureka heartbeat FAILED, Re-registering app" issue. Eureka evicted zlux from the registry because `leaseInfo` was incorrect.
> Fix lease info for APIML

- plugins/sso-auth/lib/ssoAuth.js
Related to https://github.com/zowe/zlux-app-server/pull/126
This is the case in which the plugin does not detect apiml, but does detect zss. The conditional never resolved, so the user was never shown the logout screen.
> Resolve when apiml is not in use

- lib/auth-manager.js
- lib/index.js
- plugins/sso-auth/lib/apimlHandler.js
sso-auth was re-reading CA files, and this was wrong because CA can be in a keyring instead of a file. The server loads the CA content correctly, but the plugin did not.
So, it seems best to give the server output to the security plugins so that they can re-use it. This should fix sso-auth use with keyrings.
> Add tlsOptions from server to security plugin context, for reuse

- CHANGELOG.md
- plugins/sso-auth/lib/ssoAuth.js
Fix for regression where session would expire prematurely because app server would not request a refresh from ZSS
The problem: if apiml was being used, plugin would report refresh isnt supported, even though it's partially supported. This meant that the session would expire when the shorted session timer (zss, 1 hour) expired, rather than allowing it to renew until hitting the non-expiring, longer apiml one.
This issue did not occur with sso, but did occur when using non-sso apiml+zss.
> Bugfix for zss refresh not being issued

- CHANGELOG.md
- plugins/config/lib/configService.js
- plugins/terminal-proxy/lib/assets/i18n/log/messages_en.json
- plugins/terminal-proxy/lib/terminalProxy.js
Fixes to reduce need to copy files during installation, and to bugfix an edge case where there was no instance_dir equivalent to a root_dir setting file
Previously, terminal handlers could only exist within ROOT_DIR. This was just overlooked during CUPIDS work, now it can live in the workspace dir of the plugin within the app-server.
Previously, serverside plugin config had to exist within the instance directory, meaning plugins had to perform a copy operation during installation. Now, this should be able to exist within the plugins own folder, like other configuration files.
> Bugfix for plugin default config and terminal handler location

- lib/assets/i18n/log/messages_en.json
- lib/webapp.js
- plugins/sso-auth/lib/zssHandler.js
How it works:
By default, every request to a URL on the app server which can read or modify data as opposed to those which only send read-only content like image files, will be checked to see if the request contains an http "referer" header which matches one that is valid to the server. If the header is missing or does not match one of the acceptable values, the request is denied.
The acceptable values are controlled by environment variables.
The behavior is:
if ZWE_REFERRER_HOSTS exists, use it as a comma-separated list of values
else if ZWE_REFERER_HOSTS , use it instead
if neither exist, the set of values is a combination of:
system hostname, ZOWE_EXPLORER_HOST, and ZWE_EXTERNAL_HOSTS (ZWE, not ZOWE. another comma-separated list), and the value of all IPs the server is binding to.
In …
> Reject REST requests that have wrong referer header

- lib/webapp.js
Browsers attempt to correct capitalization in hostnames, so making the server match this lower case should give protection against different casing in user input.
> Bugfix to use lower casing for all referrer use

- CHANGELOG.md
- plugins/sso-auth/lib/ssoAuth.js
See changelog for details.
sso-auth incorrectly identified refresh as being supported when using zss, but in reality it's only supported when using zss AND NOT sso, as the zss cookie is needed for this purpose, and not present in sso.
> Bugfix for session renewal error when using SSO

- utils/install-app.js
In a dev install, missing INSTANCE_DIR would result in an error when attempting to log another error.
> Correcting log function

- lib/webapp.js
When RBAC enabled there is a need to call `saf-auth` root service from auth handlers. This PR injects root services into all proxied root services that require auth just before the auth middleware.
> Inject root services into all proxied root services that require auth

- CHANGELOG.md
- lib/webapp.js
Allow a subset of env info out to the browser for dependency checks and improved server-to-server communication
To get all environment details, rbac must be on and the person must effectively be an admin, but this change is for much less info for non-admins.
> Present component and port data to web for dependency checks

- lib/util.js
This pull request fixes this following issue:
- If env var is not present, attempt to use the default zowe keystore password when decoding pkcs#12 files
> Fix fallback password

- CHANGELOG.md
- lib/util.js
This pull request adds the following feature:
- Add support for DER (binary) encoded X.509 certificates. This feature is based upon file content not file extension.
> Support for DER (binary) encoded X.509 Certificates

- lib/util.js
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>
Added new option for using `ZOWE_EXPLORER_HOST`
and parsing `Referer` now, instead of `req.hostname`
> refactor makeRemoteUrl, add ZOWE_EXPLORER_HOST option

- plugins/sso-auth/lib/zssHandler.js
This PR makes use of https://github.com/zowe/zowe-common-c/pull/194 for sso-auth
since sso-auth also uses apiml, the behavior will be:
if apiml is used and zss is used but the zss expiration is shorter than apiml: zss expiration info is sent to desktop
if apiml is used and zss is used but the zss expiration is longer than apiml: apiml expiration info is sent to desktop
if apiml is used and zss is used but the zss never expires: apiml expiration info is sent to desktop
if only zss is used: zss expiration info is sent to desktop
sso-auth used to have a default value for expiration, but practically speaking it should never need to use it now that zss can send the header. but in case someone has an out of date zss, we'll still use the default for compatibility.
keep in mind both …
> Utilize session timeout info when zss provides it

- lib/webapp.js
This pull request implements the following feature:
- Add loopback ip to referrer check if it exists but is not set to bind to the app servers IP array
Related: https://github.com/zowe/zlux-app-server/pull/143
> Add loopback ip to referrer check if it is not bound to app server

- lib/unp-constants.js
remove rsa_with_aes gcm and cbc ciphers to improve baseline cipher security
> Update cipher list

- CHANGELOG.md
- lib/index.js
Resolves https://github.com/zowe/zlux/issues/566 
Depends upon https://github.com/zowe/zlux-app-server/pull/153
> Use fully qualified hostname for eureka if available

- lib/webapp.js
This a is a hotfix for an error during app-server startup when RBAC is enabled:
```
ZWED5019E - Could not start the server:  TypeError: Cannot read property 'tlsOptions' of undefined
at Object.server (/u/ts3215/zlux-test/share/zlux-server-framework/lib/webapp.js:548:121)
at WebApp.installRootServices (/u/ts3215/zlux-test/share/zlux-server-framework/lib/webapp.js:1460:63)
at WebApp.init (/u/ts3215/zlux-test/share/zlux-server-framework/lib/webapp.js:1926:10)
at Server.<anonymous> (/u/ts3215/zlux-test/share/zlux-server-framework/lib/index.js:224:17)
at Generator.next (<anonymous>)
at Generator.tryCatcher (/u/ts3215/zlux-test/share/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
at PromiseSpawn._promiseFulfilled …
```
> Hotfix: Provide correct tlsOptions when RBAC is enabled

- CHANGELOG.md
- lib/apiml.js
- lib/index.js
- lib/plugin-loader.js
- lib/util.js
- lib/webapp.js
- plugins/sso-auth/lib/ssoAuth.js
- plugins/sso-auth/lib/zssHandler.js
This code cleans up a lot of code related to how to contact zss, in order to enhance the calling to call through apiml if zss is available through apiml.
This seems to work, but it might need additionally a loop to retry contacting apiml like we do with zss directly, to avoid timing errors. But, we do at elast wait until we register with apiml to try to find zss there.
> Adding code to conditionally contact zss thru apiml

- lib/apiml.js
This commit either includes or does not include the app-servers certificate when contacting the apiml /eureka endpoints, either for finding zss or for registering the app-server.
We found issues, either openssl protocol ones, or apiml rejecting requests with a 403, depending upon whether the app-server did/didnt send certs, and whether the certs were in the same keystore as what apiml was reading, and if the app-server used the same keystore as apiml. This code essentially sends certs in all normal circumstances except a dev environment, which it detects by checking for the env var KEYSTORE_DIRECTORY.
It has been tested with https://github.com/zowe/zowe-install-packaging/pull/2098 both through automation and through setting it up on z/os, and using a dev app-server outside z/os to see how …
> APIML cert bugfixes

- lib/webapp.js
- test/storage/apimlStorageViaUnified.js
This PR passes missing `logger` arg to `PluginStorageFactory`. The arg is mandatory.
> Pass logger to PluginStorageFactory

- lib/index.js
Use `node.mediationLayer.server.gatewayHostname` to configure Caching Service
> Use gatewayHostname to configure Caching Service

- CHANGELOG.md
- lib/apiml.js
- lib/index.js
- lib/plugin-loader.js
- lib/util.js
- lib/webapp.js
This PR moves some info logs to debug, due to being annoying and never having been useful in our troubleshooting.
Many are duplicate in purpose, or possible to derive from other logs.
And when it comes to duplicate logs, we also have a startup problem in cluster mode.
During init, all workers in a cluster do the same tasks in parallel, resulting in many log messages that say the same thing times the number of workers running.
After init, worker logging stops being duplicated due to requests being dispatched to individual workers, so duplication is only a startup problem.
To prevent duplication, I thought it would be good to reduce server core logger verbosity at startup for all workers except the first. Then when startup is finished, restore the verbosity to the requested level.
Another …
> Decrease duplicate and verbose logs

- CHANGELOG.md
- lib/proxy.js
- lib/util.js
- lib/webapp.js
This PR makes requests to zss work through APIML Gateway. The fix removes `origin` header from the HTTP request when accessing ZSS via APIML Gateway.
This PR addresses Issue: https://github.com/zowe/zlux/issues/640
```
ZWED_agent_mediationLayer_enabled=true
```
> Make requests to zss work through APIML Gateway

- lib/index.js
This PR fixes the error that appears in the log when `logLevels` is undefined:
```
ZWED0151W - unhandledRejection TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Server.restoreWorkerLogging (/ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/lib/index.js:442:23)
at Server.pluginLoadingFinished (/ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/lib/index.js:428:12)
at pluginLoaded.then (/ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/lib/index.js:362:20)
at tryCatcher (/ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/ZOWE/staging/zowe/components/app-server/share/zlux-server-framework/node_ …
```
> Fix for "TypeError: Cannot convert undefined or null to object" when logLevels is undefined

- CHANGELOG.md
- lib/webapp.js
Removes 'x-powered-by' header as it is recommended not to disclose this sever info in general.
You can see if responses from the app-server do or do not contain the header 'x-powered-by' from before and after this patch. this patch should have the header missing.
> Remove unused metadata header

- lib/webapp.js
- lib/webauth.js
- plugins/sso-auth/lib/zssHandler.js
Referrer-based checking has been annoying when external host names dont match what is expected, and with all supported browsers now supporting samesite cookie attribute, it seems to be a more elegant way to do the same thing so that users do not need to mess with their config to have proper checks being done.
> Set cookies to be samesite rather than using referrer check

- CHANGELOG.md
- plugins/sso-auth/lib/apimlHandler.js
- plugins/sso-auth/lib/zssHandler.js
This will allow users in the desktop to see more about why a login failed, as currently we hide the server message. With this PR, servers are responsible for how much info they disclose as it can be seen in the desktop, but this should have been their responsibility from the beginning, and I don't see any info coming out of zss or apiml that are security risks to forward.
> Forward server response up to browser

- lib/webserver.js
This PR adds ability to enable TLS trace. New environment variable that controls the TLS trace is
```bash
ZWED_node_https_enableTrace=true
```
> Ability to enable TLS trace

- CHANGELOG.md
- lib/index.js
- lib/webapp.js
callService and callRootService currently do a loopback where there's a request from app-server to itself in order to reach the right part of the code to handle a request. This is overhead and causes ip config complications about how app-server reaches itself.
This PR fixes the problem in two ways.
1) agent-bound routes no longer need loopback, as the call is direct. This may solve situations such as https://github.com/zowe/zlux/issues/676
2) inter-server requests can be handled internally by mimicking a network request, providing the right url, method, headers and body to the router function attached to expressjs
*Note* 2, inter-server direct routing is disabled here for compatibility. It should be very compatible, but just …
> direct routing

- CHANGELOG.md
- lib/index.js
- plugins/sso-auth/lib/apimlHandler.js
VERIFY_CERTIFICATES=true/false should apply globally but seems not to be the case in app-server. This is a fix for the case of contacting apiml for auth actions.
> Enable app-server to reach apiml when in kubernetes if using self-signed

- package-lock.json
- package.json
- utils/yamlConfig.js
This PR provides an utility that 
* reads zowe.yaml
* merges app-server and zss configs into a single config
* exports a function to get the final config
* provides ability to convert the final config into a set of `export` statements that set corresponding environment variables 
Note: Values from `app-server` config in zowe.yaml take higher priority than `zss` ones.
> Load zowe.yaml

- CHANGELOG.md
- lib/assets/i18n/log/messages_en.json
- lib/proxy.js
Proxy.js responds to a proxy error by telling the requestor that an error happened. However, this was done in a way that would send headers, but due to proxying the headers might already be sent before. This will throw an exception.
So, this PR fixes the issue by checking if the headers were sent, and if not, sending the error message. However, if the headers were sent, it instead just ends the response without adding new info.
This could be tested by having a server that starts sending data to app-server but then crashes or has some sort of socket error on purpose. Before, a worker or server crash would happen. After, it would not.
> Bugfix for proxy throwing on server error

- utils/yamlConfig.js
Signed-off-by: Leonty Chudinov <lchudinov@rocketsoftware.com>
This PR fixes zowe.yaml loading in v2 production by using new environment variables specific to v2.
> Fix zowe.yaml loading in v2 production
